import Background from "./Background"
import Elements from "./Elements"
import Text from "./Text"
import Templates from "./Templates"
import Search from "./Search"
import Images from "./Images"
import Graphics from "./Graphics"
import Pixabay from "./Pixabay"
import Uploads from "./Uploads"
import Logo from "./Logo"
import Compress from "./Compress"
import Expand from "./Expand"
import Undo from "./Undo"
import Redo from "./Redo"
import Layers from "./Layers"
import Refresh from "./Refresh"
import TimePast from "./TimePast"
import AddCircleOutline from "./AddCircleOutline"
import RemoveCircleOutline from "./RemoveCircleOutline"
import InformationCircleOutline from "./InformationCircleOutline"
import Customize from "./Customize"
import SwapHorizontal from "./SwapHorizontal"
import ArrowBackOutline from "./ArrowBackOutline"
import Underline from "./Underline"
import Add from "./Add"
import Video from "./Video"
import PhotAILogo from "./PhotAILogo"
import ActivityIcon from "./ActivityIcon"
import ProfileIcon from "./ProfileIcon"
import CanvasResize from "./CanvasResize"
import Transparency from "./Transparency"
import Share from "./Share"
import Save from "./Save"
import UploadBaseIcon from "./UploadBaseIcon"
import TextIcon from "./TextIcon"
import StockImg from "./StockImg"
import SliderIcon from "./SliderIcon"
import SliderBtn from "./SliderBtn"
import Plus from "./Plus"
import ArrowDown from "./ArrowDown"
import FacebookPost from "./FacebookPost"
import FacebookCover from "./FacebookCover"
import InstgaramR from "./InstagramR"
import Presentation4_3 from "./Presentation4_3"
import Presentation16_9 from "./Presentation16_9"
import SocialMediaStory from "./SocialMediaStory"
import YoutubeThumbNail from "./YoutubeThumbanil"
import TwitterPost from "./TwitterPost"
import BgRemover from "./BgRemover"
import ImagineAi from "./ImagineAI"
import CircleIcon from "./CircleIcon"
import Upload from "./Upload"
import Trash from "./Trash"
import ChevronRight from "./ChevronRight"
import InputContainer from "./InputContainer"
import GoogleDrive from "./GoogleDrive"
import GooglePhotos from "./GooglePhotos"
import Phone from "./Phone"
import DropBox from "./Dropbox"
import Selection from "./Selection"
import SearchIcon from "./SearchIcon"
import Adjust from "./Adjust"
import Drop from "./Drop"
import Filter from "./Filter"
import Image from "./Image"
import Outline from "./Outline"
import Reflection from "./Reflection"
import SelectionBack from "./SelectionBack"
import Texture from "./TextureIcon"
import TrashIcon from "./TrashIcon"
import ChevronDown from "./ChevronDown"
import Blur from "./Blur"
import Transform from "./Transform"
import ColorPlus from "./ColorPlus"
import GroupIcon from "./GroupIcon"
import Flip from "./Flip"
import PopupCloseIcon from "./PopupCloseIcon"
import GoogleIcon from "./GoogleIcon"
import CirclePlus from "./CirclePlus"
import Cross from "./Cross"
import ToolTipCross from "./TooltipCross"
import ToolTip from "./Tooltip"
import ImgLock from "./ImgLock"
import NoneIcon from "./NoneIcon"
import TickIcon from "./TickIcon"
import ArrowLeft from "./ArrowLeft"
import Brush from "./Brush"
import Retry from "./Retry"
import ImageUpscaler from "./ImageUpscaler"
import PhotoEditor from "./PhotoEditor"
import ObjectRemover from "./ObjectRemover"
import ImageColorizer from "./ImageColorizer"
import ObjectReplacer from "./ObjectReplacer"
import ProductPhotoshoot from "./ProductPhotoshoot"
import ArrowLeft from "./ArrowLeft"
import RetryImg from "./RetryImg"
import Upgrade from "./Upgrade"
import CreateRounded from "./CreateRounded"
import AiTools from "./AiTools"
import Assets from "./Assets"
import Designs from "./Designs"
import sideBarTempletes from "./sideBarTempletes"
import ManageSubs from "./ManageSubs"
import Settings from "./Settings"
import RightArrow from "./RightArrow"
import DownArrow from "./DownArrow"
import UpArrow from "./UpArrow"
import SearchBarIcon from "./SearchBarIcon"
import BatchUpload from "./BatchUpload"
import CreateScratch from "./CreateScratch"
import Brand from "./Brand"
import AiProfessionalPhotoshoot from "./AiProfessionalPhotoshoot"
import ImageLightFixer from "./ImageLightFixer"
import PopupClose from "./PopupClose"
import DownArrowFilled from "./DownArrowFilled"
import FileIcon from "./FileIcon"
import RenamePencil from "./RenamePencil"
import DownloadSimple from "./DownloadSimple"
import TrashSimple from "./TrashSimple"
import KebabMenu from "./KebabMenu"
import ClosedFilled from "./CrossFilled"
import RightTickMark from "./RightTickMark"
import CommingSoon from "./CommingSoon"
import CreateBrandPlus from "./CreateBrandPlus"
import DeleteIcon from "./DeleteIcon"
import ColorSelecter from "./ColorSelector"
class Icons {
  static GoogleIcon = GoogleIcon
  static PopupCloseIcon = PopupCloseIcon
  static GroupIcon = GroupIcon
  static Background = Background
  static Elements = Elements
  static Text = Text
  static Templates = Templates
  static Search = Search
  static Images = Images
  static Videos = Video
  static Graphics = Graphics
  static Pixabay = Pixabay
  static Uploads = Uploads
  static Logo = Logo
  static Compress = Compress
  static Expand = Expand
  static Undo = Undo
  static Redo = Redo
  static Refresh = Refresh
  static Layers = Layers
  static TimePast = TimePast
  static AddCircleOutline = AddCircleOutline
  static RemoveCircleOutline = RemoveCircleOutline
  static InformationCircleOutline = InformationCircleOutline
  static Customize = Customize
  static SwapHorizontal = SwapHorizontal
  static ArrowBackOutline = ArrowBackOutline
  static Underline = Underline
  static Add = Add
  static PhotAILogo = PhotAILogo
  static ProfileIcon = ProfileIcon
  static ActivityIcon = ActivityIcon
  static CanvasResize = CanvasResize
  static Transparency = Transparency
  static Share = Share
  static Save = Save
  static StockImg = StockImg
  static UploadBaseIcon = UploadBaseIcon
  static TextIcon = TextIcon
  static SliderBtn = SliderBtn
  static SliderIcon = SliderIcon
  static Plus = Plus
  static ArrowDown = ArrowDown
  static FacebookPost = FacebookPost
  static FacebookCover = FacebookCover
  static InstgaramR = InstgaramR
  static Presentation4_3 = Presentation4_3
  static Presentation16_9 = Presentation16_9
  static SocialMediaStory = SocialMediaStory
  static YoutubeThumbNail = YoutubeThumbNail
  static TwitterPost = TwitterPost
  static BgRemover = BgRemover
  static ImagineAi = ImagineAi
  static CircleIcon = CircleIcon
  static Upload = Upload
  static Trash = Trash
  static ChevronRight = ChevronRight
  static InputContainer = InputContainer
  static DropBox = DropBox
  static GooglePhotos = GooglePhotos
  static GoogleDrive = GoogleDrive
  static Phone = Phone
  static Selection = Selection
  static SearchIcon = SearchIcon
  static Adjust = Adjust
  static Drop = Drop
  static Filter = Filter
  static Image = Image
  static Outline = Outline
  static SelectionBack = SelectionBack
  static Reflection = Reflection
  static Texture = Texture
  static TrashIcon = TrashIcon
  static ChevronDown = ChevronDown
  static Blur = Blur
  static Transform = Transform
  static ColorPlus = ColorPlus
  static Flip = Flip
  static CirclePlus = CirclePlus
  static Cross = Cross
  static ToolTipCross = ToolTipCross
  static ToolTip = ToolTip
  static ImgLock = ImgLock
  static NoneIcon = NoneIcon
  static TickIcon = TickIcon
  static ArrowLeft = ArrowLeft
  static Brush = Brush
  static Retry = Retry
  static ImageUpscaler = ImageUpscaler
  static PhotoEditor = PhotoEditor
  static ObjectRemover = ObjectRemover
  static ImageColorizer = ImageColorizer
  static ObjectReplacer = ObjectReplacer
  static ProductPhotoshoot = ProductPhotoshoot
  static ArrowLeft = ArrowLeft
  static RetryImg = RetryImg
  static Upgrade = Upgrade
  static CreateRounded = CreateRounded
  static AiTools = AiTools
  static Assets = Assets
  static Designs = Designs
  static sideBarTempletes = sideBarTempletes
  static ManageSubs = ManageSubs
  static Settings = Settings
  static RightArrow = RightArrow
  static DownArrow = DownArrow
  static UpArrow = UpArrow
  static SearchBarIcon = SearchBarIcon
  static BatchUpload = BatchUpload
  static CreateScratch = CreateScratch
  static Brand = Brand
  static AiProfessionalPhotoshoot = AiProfessionalPhotoshoot
  static ImageLightFixer = ImageLightFixer
  static PopupClose = PopupClose
  static DownArrowFilled = DownArrowFilled
  static FileIcon = FileIcon
  static RenamePencil = RenamePencil
  static DownloadSimple = DownloadSimple
  static TrashSimple = TrashSimple
  static KebabMenu = KebabMenu
  static ClosedFilled = ClosedFilled
  static RightTickMark = RightTickMark
  static CommingSoon = CommingSoon
  static CreateBrandPlus = CreateBrandPlus
  static DeleteIcon = DeleteIcon
  static ColorSelecter = ColorSelecter
}

export default Icons
